server:
  port: 8081
# 项目信息
item:
  version: 1.0.0
  title: 蔡燃后台管理系统
spring:
  #数据库配置
  datasource:
    #数据库连接配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/caiRanSystem?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: 1234
    #数据库连接池配置
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    #连接等待超时时间
    maxWait: 60000
    #配置隔多久进行一次检测(检测可以关闭的空闲连接)
    timeBetweenEvictionRunsMillis: 60000
    #配置连接在池中的最小生存时间
    minEvictableIdleTimeMillis: 300000
    #验证查询sql
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis= 5000

#  mvc:
#   throw-exception-if-no-handler-found: true

  #freemarker配置
  freemarker:
    request-context-attribute: req
    suffix: .ftl
    template-loader-path: classpath:/templates/

  #redis 配置
  redis:
    host: 192.168.2.164
    port: 6379
    password: 123456
    database: 3
    timeout: 3S
  #  redis连接池
  cache:
    type: redis
    redis:
      time-to-live: 2000000S #缓存超时时间ms
      cache-null-values: false #是否缓存空值


#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#mybatis配置
mybatis:
  mapper-locations: classpath*:com/caiRanSystem/dao/**/mapper/*.xml
