server:
  port: 8601

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
    refresh:
      refreshable: none


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8101/eureka/

