eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8101/eureka/

server:
  port: 8401

spring:
  application:
    name: server_zuul

  main:
    allow-bean-definition-overriding: true


zuul:
  routes:
    path: /api-b/**
    serviceId: feign
