server:
  port: 8101

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8101/eureka/

spring:
  application:
    name: eurka-server
